# Generated by Django 5.2.4 on 2026-01-20 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('points', models.JSONField()),
                ('label_x', models.FloatField()),
                ('label_y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shaft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('electricity', 'Điện'), ('ventilation', 'Thông gió'), ('water', 'Nước')], max_length=30)),
                ('x', models.FloatField()),
                ('y1', models.FloatField()),
                ('y2', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('maintenance', 'Đang bảo trì'), ('error', 'Hỏng')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('level', models.IntegerField()),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('electricity', 'Điện'), ('ventilation', 'Thông gió'), ('water', 'Nước')], max_length=20)),
                ('path', models.JSONField()),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('maintenance', 'Đang bảo trì'), ('error', 'Hỏng')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.room')),
                ('shaft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.shaft')),
            ],
        ),
        migrations.AddField(
            model_name='shaft',
            name='storey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.storey'),
        ),
        migrations.AddField(
            model_name='room',
            name='storey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.storey'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('code', 'storey')},
        ),
    ]
