const cameraDevices = [
  {
    code: "CAM001",
    name: "Camera sảnh chính",
    floor: "T1",
    location: "Sảnh chính",
    range: "5m",
    status: "active",
  },
  {
    code: "CAM002",
    name: "Camera hành lang 1",
    floor: "T1",
    location: "Hành lang HL-101",
    range: "10m",
    status: "active",
  },
  {
    code: "CAM003",
    name: "Camera thang máy 1",
    floor: "T2",
    location: "Thang máy TM-01",
    range: "4m",
    status: "active",
  },
  {
    code: "CAM004",
    name: "Camera hầm xe 1",
    floor: "B1",
    location: "Bãi xe tầng hầm B1",
    range: "5m",
    status: "maintenance",
  },
  {
    code: "CAM005",
    name: "Camera hành lang 2",
    floor: "T1",
    location: "Hành lang HL-102",
    range: "8m",
    status: "error",
  },
  {
    code: "CAM006",
    name: "Camera sân thượng 1",
    floor: "ST1",
    location: "Sân thượng",
    range: "15m",
    status: "active",
  },
  {
    code: "CAM007",
    name: "Camera thang máy 2",
    floor: "T2",
    location: "Thang máy TM-02",
    range: "4m",
    status: "maintenance",
  },
  {
    code: "CAM008",
    name: "Camera thang máy 3",
    floor: "T2",
    location: "Thang máy TM-03",
    range: "4m",
    status: "maintenance",
  },
  {
    code: "CAM009",
    name: "Camera lễ tân",
    floor: "T1",
    location: "Quầy lễ tân",
    range: "6m",
    status: "active",
  },
  {
    code: "CAM010",
    name: "Camera hành lang 3",
    floor: "T3",
    location: "Hành lang HL-301",
    range: "8m",
    status: "active",
  },
  {
    code: "CAM011",
    name: "Camera hành lang 4",
    floor: "T3",
    location: "Hành lang HL-302",
    range: "8m",
    status: "maintenance",
  },
  {
    code: "CAM012",
    name: "Camera phòng họp 1",
    floor: "T2",
    location: "Phòng họp PH-201",
    range: "6m",
    status: "active",
  },
  {
    code: "CAM013",
    name: "Camera phòng họp 2",
    floor: "T2",
    location: "Phòng họp PH-202",
    range: "6m",
    status: "active",
  },
  {
    code: "CAM014",
    name: "Camera hành lang 5",
    floor: "T4",
    location: "Hành lang HL-401",
    range: "9m",
    status: "error",
  },
  {
    code: "CAM015",
    name: "Camera bãi xe 2",
    floor: "B1",
    location: "Bãi xe tầng hầm B1",
    range: "12m",
    status: "active",
  },
  {
    code: "CAM016",
    name: "Camera kho kỹ thuật",
    floor: "B2",
    location: "Kho kỹ thuật",
    range: "7m",
    status: "maintenance",
  },
  {
    code: "CAM017",
    name: "Camera sân thượng 2",
    floor: "ST1",
    location: "Sân thượng",
    range: "15m",
    status: "active",
  },
  {
    code: "CAM018",
    name: "Camera cổng chính",
    floor: "T1",
    location: "Cổng chính",
    range: "20m",
    status: "active",
  },
];

export default cameraDevices;
