const exitDevices = [
  {
    code: "EX001",
    name: "Cầu thang bộ P01",
    floor: "T1",
    location: "P01.10",
    exitType: "stairs",
    width: "1.5",
    capacity: "75",
    distanceNearest: "25",
    coordinateX: "120.5",
    coordinateY: "85.3",
    exitDoor: "on",
    barrier: "yes",
    status: "active",
    note: "Cầu thang bộ chính, kiểm tra định kỳ hàng tháng.",
    imageUrl: "",
  },
  {
    code: "EX002",
    name: "Cửa thoát hiểm HL-101",
    floor: "T1",
    location: "HL-101",
    exitType: "door",
    width: "1.2",
    capacity: "60",
    distanceNearest: "18",
    coordinateX: "118.2",
    coordinateY: "82.4",
    exitDoor: "on",
    barrier: "no",
    status: "active",
    note: "Lối thoát hiểm hành lang 1.",
    imageUrl: "",
  },
  {
    code: "EX003",
    name: "Cầu thang bộ TM-01",
    floor: "T2",
    location: "TM-01",
    exitType: "stairs",
    width: "2.0",
    capacity: "90",
    distanceNearest: "30",
    coordinateX: "121.3",
    coordinateY: "80.1",
    exitDoor: "on",
    barrier: "yes",
    status: "active",
    note: "Kết nối khu vực thang máy.",
    imageUrl: "",
  },
  {
    code: "EX004",
    name: "Thang máy PCCC B1",
    floor: "B1",
    location: "B1.05",
    exitType: "elevator",
    width: "1.8",
    capacity: "80",
    distanceNearest: "22",
    coordinateX: "110.9",
    coordinateY: "72.4",
    exitDoor: "off",
    barrier: "yes",
    status: "maintenance",
    note: "Đang bảo trì hệ thống cứu hộ.",
    imageUrl: "",
  },
  {
    code: "EX005",
    name: "Cửa thoát hiểm ST-01",
    floor: "T1",
    location: "ST-01",
    exitType: "door",
    width: "1.0",
    capacity: "55",
    distanceNearest: "15",
    coordinateX: "124.7",
    coordinateY: "88.8",
    exitDoor: "off",
    barrier: "no",
    status: "blocked",
    note: "Bị chặn do vật liệu thi công.",
    imageUrl: "",
  },
  {
    code: "EX006",
    name: "Cầu thang bộ P02",
    floor: "T2",
    location: "P02.04",
    exitType: "stairs",
    width: "1.5",
    capacity: "75",
    distanceNearest: "20",
    coordinateX: "119.4",
    coordinateY: "81.6",
    exitDoor: "on",
    barrier: "yes",
    status: "active",
    note: "Lối thoát hiểm khu P02.",
    imageUrl: "",
  },
  {
    code: "EX007",
    name: "Cửa thoát hiểm CG-A1",
    floor: "T1",
    location: "CG-A1",
    exitType: "door",
    width: "1.2",
    capacity: "60",
    distanceNearest: "19",
    coordinateX: "121.9",
    coordinateY: "84.1",
    exitDoor: "on",
    barrier: "yes",
    status: "maintenance",
    note: "Kiểm tra chốt an toàn.",
    imageUrl: "",
  },
  {
    code: "EX008",
    name: "Cửa thoát hiểm CG-A2",
    floor: "T20",
    location: "CG-A2",
    exitType: "door",
    width: "1.2",
    capacity: "60",
    distanceNearest: "17",
    coordinateX: "123.3",
    coordinateY: "86.2",
    exitDoor: "on",
    barrier: "no",
    status: "active",
    note: "Kiểm tra tay đẩy định kỳ.",
    imageUrl: "",
  },
];

export default exitDevices;
