const fireDevices = [
  {
    code: "FIR001",
    name: "Bình chữa cháy CO2",
    floor: "T1",
    location: "Sảnh chính",
    range: "4m",
    status: "active",
  },
  {
    code: "FIR002",
    name: "Bình chữa cháy bột",
    floor: "T2",
    location: "Phòng kỹ thuật",
    range: "4m",
    status: "maintenance",
  },
  {
    code: "FIR003",
    name: "Bình chữa cháy foam",
    floor: "B1",
    location: "Bãi xe",
    range: "5m",
    status: "active",
  },
  {
    code: "FIR004",
    name: "Bình chữa cháy CO2",
    floor: "T2",
    location: "Hành lang HL-201",
    range: "4m",
    status: "active",
  },
  {
    code: "FIR005",
    name: "Bình chữa cháy bột",
    floor: "T3",
    location: "Hành lang HL-301",
    range: "4m",
    status: "maintenance",
  },
  {
    code: "FIR006",
    name: "Bình chữa cháy foam",
    floor: "T4",
    location: "Phòng họp PH-401",
    range: "5m",
    status: "active",
  },
  {
    code: "FIR007",
    name: "Bình chữa cháy CO2",
    floor: "T1",
    location: "Sảnh phụ",
    range: "4m",
    status: "active",
  },
  {
    code: "FIR008",
    name: "Bình chữa cháy bột",
    floor: "B1",
    location: "Bãi xe khu B",
    range: "4m",
    status: "error",
  },
  {
    code: "FIR009",
    name: "Bình chữa cháy foam",
    floor: "T5",
    location: "Khu bếp",
    range: "5m",
    status: "active",
  },
  {
    code: "FIR010",
    name: "Bình chữa cháy CO2",
    floor: "T4",
    location: "Phòng server",
    range: "4m",
    status: "maintenance",
  },
  {
    code: "FIR011",
    name: "Bình chữa cháy bột",
    floor: "T2",
    location: "Phòng kỹ thuật",
    range: "4m",
    status: "active",
  },
  {
    code: "FIR012",
    name: "Bình chữa cháy foam",
    floor: "B2",
    location: "Kho kỹ thuật",
    range: "5m",
    status: "maintenance",
  },
];

export default fireDevices;
