const sensorDevices = [
  {
    code: "SEN001",
    name: "Cảm biến khói sảnh chính",
    floor: "T1",
    location: "Sảnh chính",
    range: "12m",
    status: "active",
  },
  {
    code: "SEN002",
    name: "Cảm biến nhiệt hành lang",
    floor: "T2",
    location: "Hành lang HL-201",
    range: "10m",
    status: "active",
  },
  {
    code: "SEN003",
    name: "Cảm biến khí gas",
    floor: "B1",
    location: "Khu kỹ thuật",
    range: "6m",
    status: "maintenance",
  },
  {
    code: "SEN004",
    name: "Cảm biến chuyển động",
    floor: "T3",
    location: "Hành lang HL-301",
    range: "8m",
    status: "error",
  },
  {
    code: "SEN005",
    name: "Cảm biến khói phòng họp 1",
    floor: "T2",
    location: "Phòng họp PH-201",
    range: "10m",
    status: "active",
  },
  {
    code: "SEN006",
    name: "Cảm biến nhiệt phòng họp 2",
    floor: "T2",
    location: "Phòng họp PH-202",
    range: "10m",
    status: "active",
  },
  {
    code: "SEN007",
    name: "Cảm biến khí CO",
    floor: "B1",
    location: "Bãi xe",
    range: "7m",
    status: "maintenance",
  },
  {
    code: "SEN008",
    name: "Cảm biến chuyển động sảnh",
    floor: "T1",
    location: "Sảnh chính",
    range: "9m",
    status: "active",
  },
  {
    code: "SEN009",
    name: "Cảm biến khói hành lang",
    floor: "T3",
    location: "Hành lang HL-302",
    range: "10m",
    status: "active",
  },
  {
    code: "SEN010",
    name: "Cảm biến nhiệt kho",
    floor: "B2",
    location: "Kho kỹ thuật",
    range: "6m",
    status: "error",
  },
  {
    code: "SEN011",
    name: "Cảm biến khí gas bếp",
    floor: "T5",
    location: "Khu bếp",
    range: "5m",
    status: "active",
  },
  {
    code: "SEN012",
    name: "Cảm biến khói phòng server",
    floor: "T4",
    location: "Phòng server",
    range: "8m",
    status: "maintenance",
  },
];

export default sensorDevices;
